name: Drupal CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies with Composer
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Drupal PHP lint (base sintaxe verification)
        run: find web/modules/custom web/themes/custom -name '*.php' -print0 | xargs -0 -n1 php -l

      - name: Execute simple tests (status Drupal)
        run: |
          ./vendor/bin/drush status

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
